### ISSUE TITLE
missing ;

### ISSUE THREAD

**Issue by Tindyy** [misspastelwitch/look-and-feel-corporate-identity#11]
Door je styles.css mis je op een aantal lines een ; hieronder heb ik er een paar gelinkt maar je moet nog wel even de rest doorlopen om te checken.

https://github.com/misspastelwitch/look-and-feel-corporate-identity/blob/d95395023047bbfec58fad219e74870622d8cb86/styles.css#L5

https://github.com/misspastelwitch/look-and-feel-corporate-identity/blob/d95395023047bbfec58fad219e74870622d8cb86/styles.css#L41

https://github.com/misspastelwitch/look-and-feel-corporate-identity/blob/d95395023047bbfec58fad219e74870622d8cb86/styles.css#L45

https://github.com/misspastelwitch/look-and-feel-corporate-identity/blob/d95395023047bbfec58fad219e74870622d8cb86/styles.css#L55

**Comment by misspastelwitch** [comment]
Heb ik veranderd! bedankt!
